version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
        - ./projeto_delivery:/usr/app
    environment:
        FLASK_ENV: development
  redis:
    image: "redis:alpine"
